version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
